# Generated by Django 2.2.20 on 2021-04-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20210413_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='descripcion',
        ),
    ]
