# Generated by Django 2.2.20 on 2021-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_auto_20210413_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='descripcion',
            field=models.TextField(default='sth', verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
