# Generated by Django 2.2.20 on 2021-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_autor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
