# Generated by Django 2.2.20 on 2021-04-21 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20210420_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('permiso_desde_codigo', 'Este es un permiso creado desde codigo'), ('segundo_permiso_codigo', 'Segundo permiso desde codigo')]},
        ),
    ]
